name: Trigger excel2md

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  dispatch_event:
    runs-on: ubuntu-latest
    name: Dispatch event

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get version info
      id:   tag
      run: |
            NEXT_VERSION=$(./get_next.sh ${{ github.repository_owner }} excel2xml-input)
            echo "NEXT_VERSION: ${NEXT_VERSION}"
            echo ::set-output name=next-release::${NEXT_VERSION}

    - name: Create Archive
      id: create-archive
      run: |
        zip -r grupoetra excel-use-cases

    - name: Create Release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.next-release }}
        release_name: ${{ steps.tag.outputs.next-release }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./grupoetra.zip
        asset_name: grupoetra.zip
        asset_content_type: application/zip

    - uses: juztcode/repo-ditpatch-action@v1
      with:
        event-type: release_event
        token: ${{ secrets.REPO_TRIGGER_KEY }}
        repository: "${{ github.repository_owner }}/excel2xml"
        client-payload: '{"tag": "${{ steps.tag.outputs.next-release }}" }'
